# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logindate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('ldate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
